import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';


export default function Home({users}) {
  const router=useRouter();
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
      <h2>User List</h2>
      {
        users.map((user)=>(
          <div key={user.id} onClick={()=>router.push(`/user/${user.id}`)}>
            <p>{user.name} ({user.username})</p>
          </div>)
        )
      }
    </div>
  )
}

export const getStaticProps=async()=>{
  const res=await fetch('https://jsonplaceholder.typicode.com/users');
  const users=await res.json();
  return{
    props:{
      users
    }
  }
}













// export const getStaticProps=async ()=>{
//   const res=await fetch('https://jsonplaceholder.typicode.com/users');
//   const users=await res.json();

//   return{
//     props:{
//       users
//     }
//   }
// }